num_epochs: 300 # Number of Epochs for Training
seed: 2 # Random seed for training
batch_size: 8
data_input_dir: "./datasets/audio" # Directory to store bigger datafiles (dataset and audio_models)
data_output_dir: "." # Directory to store bigger datafiles (dataset and audio_models)
validate: False # Boolean to decide whether to split train dataset into train/val and plot validation loss

# If given, uses this string to create directory to save results in
# be careful, this can overwrite previous results
# otherwise saves logs according to time-stamp
save_dir: ""
calc_accuracy: False