name: cpc 
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - numpy=1.16.4
  - numpy-base=1.16.4
  - pandas=0.24.0
  - pcre=8.42
  - pillow=5.4.1
  - pip=20.0.2
  - python=3.7.6
  - pytorch=1.4.0
  - readline=7.0
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - seaborn=0.10.0
  - six=1.14.0
  - tensorboard
  - torchvision=0.5.0
  - tqdm=4.42.1
  - pip:
    - gdown==3.10.1
    - black==19.10b0
    - decorator==4.4.0
    - docopt==0.6.2
    - imageio==2.5.0
    - jsonpickle==1.3
    - munch==2.5.0
    - networkx==2.3
    - protobuf==3.7.1
    - py-cpuinfo==5.0.0
    - pymongo==3.10.1
    - pyyaml==5.3
    - pywavelets==1.0.3
    - sacred==0.8.1
    - scikit-image==0.15.0
    - toml==0.10.0
    - torchaudio -f https://download.pytorch.org/whl/torch_stable.html
    - wrapt==1.12.0
